server:
  port: 9002

spring:
  application:
    name: claim-sidecar

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

sidecar:
  port: 3000
  health-uri: http://localhost:${sidecar.port}/health