server:
  port: 8888

spring:
  application:
    name: claim-config
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
